# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7832b309ae420ebedda650e02e58e36248a2ac21ee99547f4a846555a8597af4e25e168f0f9b8927937d781bc25402943c684c6d37caaaf471a5fb2213b10db7

test:
  secret_key_base: 73e8b3e21a86c4f6cb529a53350aa4bbf0d8cd2713c8f82227b5d90fa2de59641077f7b9fb6dd31e921c4871f305809b541cfe06ef51beb5b541996556a24ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
